import type { Metadata } from "next";
import { NayldLogo } from "@/components/NayldLogo";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms and Conditions — nayld.ai",
  description: "Terms governing your use of the nayld.ai service.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white text-slate-900">
      <header className="border-b border-slate-100">
        <div className="mx-auto flex max-w-3xl items-center justify-between px-6 py-4">
          <Link href="/">
            <NayldLogo className="h-8 w-auto" />
          </Link>
          <Link href="/" className="text-sm text-slate-500 transition-colors hover:text-slate-900">
            Back to Home
          </Link>
        </div>
      </header>

      <main className="mx-auto max-w-3xl px-6 py-16">
        <h1 className="text-3xl font-bold tracking-tight text-slate-900 sm:text-4xl">
          Terms and Conditions
        </h1>
        <p className="mt-2 text-sm text-slate-500">Last updated: February 18, 2026</p>

        <div className="prose prose-slate mt-10 max-w-none prose-headings:font-semibold prose-headings:tracking-tight prose-h2:text-xl prose-h2:mt-10 prose-h2:mb-4 prose-p:leading-relaxed prose-li:leading-relaxed">
          <p>
            These Terms and Conditions (&quot;Terms&quot;) govern your use of the nayld.ai website
            and service, operated by NayldAi. By creating an account or using the service, you agree to these Terms.
          </p>

          <h2>1. The Service</h2>
          <p>
            nayld.ai is an AI-powered interview preparation platform. You can upload your resume, add
            job descriptions, receive fit analysis, and participate in AI mock interviews. The service
            provides AI-generated feedback intended to help you prepare &mdash; it does not guarantee
            employment outcomes.
          </p>

          <h2>2. Accounts</h2>
          <ul>
            <li>You must provide accurate information when creating an account.</li>
            <li>You are responsible for maintaining the security of your account credentials.</li>
            <li>You must be at least 16 years of age to use the service.</li>
            <li>
              We reserve the right to suspend or terminate accounts that violate these Terms.
            </li>
          </ul>

          <h2>3. Billing &amp; Credits</h2>
          <ul>
            <li>
              nayld.ai operates on a credit-based system. Each mock interview session consumes one
              interview credit.
            </li>
            <li>
              <strong>Subscriptions:</strong> The Standard plan ($15/month, 2 credits per cycle) and
              Pro plan ($29/month, 5 credits per cycle) renew automatically. You may cancel at any
              time; cancellation takes effect at the end of the current billing cycle.
            </li>
            <li>
              <strong>One-off credits:</strong> Purchased at $10 per credit. One-off credits do not
              expire and stack with subscription credits.
            </li>
            <li>
              Prices are subject to change. We will notify existing subscribers at least 30 days
              before any price increase takes effect on their account.
            </li>
          </ul>

          <h2>4. User Content</h2>
          <ul>
            <li>You retain ownership of all content you upload (resumes, job descriptions).</li>
            <li>
              By uploading content, you grant nayld.ai a limited licence to process, store, and
              analyse it solely for the purpose of providing the service to you.
            </li>
            <li>
              You are responsible for ensuring you have the right to upload any content you submit.
            </li>
            <li>
              Do not upload content that is illegal, defamatory, or infringes on the rights of
              others.
            </li>
          </ul>

          <h2>5. AI-Generated Content</h2>
          <ul>
            <li>
              Fit scores, interview questions, performance assessments, and other AI outputs are
              generated by automated systems.
            </li>
            <li>
              AI-generated content is provided for informational and preparation purposes only. It
              should not be relied upon as professional career advice.
            </li>
            <li>
              We do not guarantee the accuracy, completeness, or suitability of AI-generated outputs.
            </li>
          </ul>

          <h2>6. Prohibited Use</h2>
          <p>You may not:</p>
          <ul>
            <li>Use the service for any unlawful purpose.</li>
            <li>
              Attempt to reverse-engineer, scrape, or extract data from the platform.
            </li>
            <li>
              Share your account credentials with others or resell access to the service.
            </li>
            <li>Submit content that contains malware or is intended to disrupt the service.</li>
          </ul>

          <h2>7. Service Availability</h2>
          <p>
            We strive to maintain continuous availability but do not guarantee uninterrupted access.
            We may perform maintenance, updates, or modifications to the service at any time. We are
            not liable for any downtime or data loss resulting from service interruptions.
          </p>

          <h2>8. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by law, nayld.ai and its operators shall not be liable
            for any indirect, incidental, or consequential damages arising from your use of the
            service. Our total liability for any claim related to the service shall not exceed the
            amount you have paid us in the 12 months preceding the claim.
          </p>

          <h2>9. Changes to These Terms</h2>
          <p>
            We may update these Terms from time to time. We will notify registered users of material
            changes via email. Continued use of the service after changes constitutes acceptance.
          </p>

          <h2>10. Governing Law</h2>
          <p>
            These Terms are governed by and construed in accordance with applicable law. Any disputes
            shall be resolved through good-faith negotiation before pursuing formal proceedings.
          </p>

          <h2>11. Contact Us</h2>
          <p>
            If you have questions about these Terms, contact us at{" "}
            <a href="mailto:hello@nayld.ai" className="text-mm-violet hover:underline">
              hello@nayld.ai
            </a>
            .
          </p>
        </div>
      </main>

      <footer className="border-t border-slate-100 py-6">
        <div className="mx-auto flex max-w-3xl items-center justify-between px-6">
          <p className="text-xs text-slate-400">
            &copy; {new Date().getFullYear()} nayld.ai. All rights reserved.
          </p>
          <nav className="flex gap-6 text-xs text-slate-500">
            <Link href="/terms" className="hover:text-slate-900">Terms</Link>
            <Link href="/refund" className="hover:text-slate-900">Refund</Link>
            <Link href="/privacy" className="hover:text-slate-900">Privacy</Link>
          </nav>
        </div>
      </footer>
    </div>
  );
}
